services:
  hyperplanning-bot:
    build: .
    container_name: hyperplanning-bot
    restart: unless-stopped
    environment:
      - HP_URL=${HP_URL}
      - HP_USERNAME=${HP_USERNAME}
      - HP_PASSWORD=${HP_PASSWORD}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      - CHECK_INTERVAL_SECONDS=3600 # VÃ©rification toutes les heures
      - HEADLESS_MODE=True
      - AUTH_STATE_JSON=${AUTH_STATE_JSON}
      - LOG_TIMEZONE=${LOG_TIMEZONE}
    volumes:
      - hyperplanning_data:/app/data

volumes:
  hyperplanning_data:
